### ISSUE TITLE
Files are not imported into Neo4j Database

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [rd-switchboard/Inference#35]
I compiled the Inference project using maven run the following command: java -jar import_ands-1.4.0.jar properties/import_ands.properties
However, no files were imported: 
XML: xml/ands
Done
Processed 0 files.
Spent 0 millisecods.
Found 0 records.
Found 0 deleted records.
Found 0 broken records.
Spent ~ NaN milliseconds per record.
0 nodes has been created.
0 nodes has been updated.
0 relationships has been created.
0 relationships has been updated.
0 relationships keys has been invalid.

Import_ands.properties:

s3.bucket:xml.rd-switchboard
# Path to local XML folder

ands.xml=xml/ands
# Type of the XML (oai or rif_cs). The default is oai

ands.xml.type=rif_cs
neo4j:/home/anusuriya/Documents/Neo4j-Browser/distribution/neo4j/

**Comment by wizman777** [comment]
Hi

In order for Import program to work, it must have access to the AWS S3 bucket where files have been harvested via OAI:PMH harvesting program: https://github.com/rd-switchboard/Harvesters/tree/master/OAI_PMH/harvester_oai

Have you got access to that bucket? Can you please test it? Thanks

**Comment by kitchenprinzessin3880** [comment]
Hi.
Sorry i haven't fully grasped yet the interactions between different modules of the switchboard. How can I test if I have an access to the bucket?

**Comment by wizman777** [comment]
Hi

The import_ands program will read RIF-CS files from provided repository and will import it into local Neo4j instance. Two forms of repositories are accessible: 

1) Local folder
2) S3 bucket

At this moment only designated EC2 machines has access to our S3 bucket, so you probably will not have such access from your local computer.

But you can import files from your local folder. To do that, just copy them into any folder on your computer, and add `ands.xml` parameter into import_ands configuration file:

ands.xml=/path/to/your/local/repository

You will also need to delete or comment out `s3.bucket` and `ands.s3` parameters.

If you want to test import from S3 repository instead, you can do that as well. Just create any S3 repository and use OAI-PMH harvester to harvest data to it. The harvester can be found at https://github.com/rd-switchboard/Harvesters/tree/master/OAI_PMH/harvester_oai and it will harvest files into provided S3 bucket. It can harvest them into your local folder as well. in case you need extract files from some OAI-PMH provider.

**Comment by wizman777** [comment]
To answer your previous question, the easiest way to test S3 accessibility, would be to use AWS client https://aws.amazon.com/cli/ and try list the bucket and download something. The command to list bucket is

aws s3 ls s3://bucket_name

the command to download

aws s3 cp s3://bucket_name/file_name local_file_name
